services:
  - type: web
    name: tradingview-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_actual_bot_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id